train:
  # ...

  data_preprocessor:
    # only imputation and scaling are done by default, other steps can be skipped.
    params:
      imputer_strategy: 'mean'
      scale: 'standardize'  # standard scaling or minmax scaling (minmax)
      include_column_selector: true  # whether to apply the ColumnSelector
      max_nan_frac_per_col: 0.05  # ColumnSelector option - drop columns where >5% is NaN.
      features_to_exclude: # ColumnSelector option - features to always exclude
        - feature1
        - feature2
      angles:  # list of angles to transform to sine/cosine values; skipped if none provided
        - angle1
        - angle2
      include_low_unique_value_filter: true  # whether to apply the LowVarianceFilter
      min_unique_value_count: 2  # LowVarianceFilter option - drop columns with less than 3 unique values
      max_col_zero_frac: 0.99  # LowVarianceFilter option - drop columns which are at least 90% zero
      include_duplicate_value_to_nan: false  # whether to apply the DuplicateValuesToNan
      value_to_replace: 0  # DuplicateValuesToNan option - if duplicated, replace duplicates with NaN
      n_max_duplicates: 6  # DuplicateValuesToNan option - if duplicated for n_max_duplicates, replace after 6th value with NaN
      duplicate_features_to_exclude:  # DuplicateValuesToNan option - list of feature to not transform with DuplicateValuesToNan
        - do_not_replace_value_with_nan

   # ...
